version: '3'
services:
  api:
    build: .
    container_name: cafetaria_api
    ports:
      - '8080:8080'
    env_file:
      - .env
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SERVER=${SERVER}
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - postgres
    command: npm run start:prod

  postgres:
    image: postgres:14-alpine
    container_name: postgres_db_cafetaria
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5435:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $DB_USER -d $DB_NAME']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
